### ISSUE TITLE
Fails to build against libxml 2.14

### ISSUE THREAD

**Issue by sthibaul** [liblouis/liblouisutdml#118]
Hello,

As noticed in debian, liblouisutdml does not build with libxml 2.14:
http://qa-logs.debian.net/2025/05/23/liblouisutdml_2.12.0-7_unstable_libxml2.log

Samuel

**Comment by sthibaul** [comment]
But it's about ATTRIBUTE_UNUSED, unrelated to libxml2:

```
louisutdml.h:373:31: error: expected ';', ',' or ')' before 'ATTRIBUTE_UNUSED'
  373 | void libxml_errors (void *ctx ATTRIBUTE_UNUSED, const char *msg, ...);
```

**Comment by arekm** [comment]
While building with libxml2-2.14.5

````
/usr/include/libxml2/libxml/parser.h:1128:17: note: declared here
 1128 |                 xmlThrDefLineNumbersDefaultValue(int v);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/libxml2/libxml/valid.h:16,
                 from /usr/include/libxml2/libxml/parser.h:20:
transcriber.c: In function 'processDaisyDoc':
/usr/include/libxml2/libxml/xmlerror.h:23:45: error: invalid use of void expression
   23 |     xmlSetGenericErrorFunc(NULL, (h) ? *(h) : NULL)
      |                                             ^
transcriber.c:4065:3: note: in expansion of macro 'initGenericErrorDefaultFunc'
 4065 |   initGenericErrorDefaultFunc (NULL);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
transcriber.c: In function 'freeDaisyDoc':
/usr/include/libxml2/libxml/xmlerror.h:23:45: error: invalid use of void expression
   23 |     xmlSetGenericErrorFunc(NULL, (h) ? *(h) : NULL)
      |                                             ^
transcriber.c:4083:3: note: in expansion of macro 'initGenericErrorDefaultFunc'
 4083 |   initGenericErrorDefaultFunc (NULL);
````


which were fixed by

````
diff --git a/liblouisutdml/liblouisutdml.c b/liblouisutdml/liblouisutdml.c
index 2fbd761..6e8345e 100644
--- a/liblouisutdml/liblouisutdml.c
+++ b/liblouisutdml/liblouisutdml.c
@@ -79,7 +79,7 @@ cleanupLibxml ()
   if (!libxml2_initialized)
     return;
   xmlCleanupParser ();
-  initGenericErrorDefaultFunc (NULL);
+  xmlSetGenericErrorFunc (NULL, NULL);
   xmlFreeParserCtxt (ctxt);
 }

diff --git a/liblouisutdml/transcriber.c b/liblouisutdml/transcriber.c
index 07d7b5a..e39d8f2 100644
--- a/liblouisutdml/transcriber.c
+++ b/liblouisutdml/transcriber.c
@@ -4062,7 +4062,7 @@ processDaisyDoc ()
   transcribe_document (rootElement);
   xmlFreeDoc (ud->doc);
   xmlCleanupParser ();
-  initGenericErrorDefaultFunc (NULL);
+  xmlSetGenericErrorFunc (NULL, NULL);
   xmlFreeParserCtxt (ctxt);
   return 1;
 }
@@ -4080,7 +4080,7 @@ makeDaisyDoc but not
     }
   xmlFreeDoc (ud->doc);
   xmlCleanupParser ();
-  initGenericErrorDefaultFunc (NULL);
+  xmlSetGenericErrorFunc (NULL, NULL);
   xmlFreeParserCtxt (ctxt);
   return 1;
 }
````
